from hydra import *

FILE_HEADER = """/**
 * This file was auto-generated by the Hydra library emitter.
 * Hail Hydra!
 *
 * Source file: {source_name}
 * Timestamp:   {timestamp}
 */

{includes}

#pragma pack(push, 1)

{structs}
#pragma pack(pop)
"""

SCALAR_LEXICON = {
        uint8_t:   'uint8_t',
        uint16_t:  'uint16_t',
        uint32_t:  'uint32_t',
        uint64_t:  'uint64_t',
        int8_t:    'int8_t',
        int16_t:   'int16_t',
        int32_t:   'int32_t',
        int64_t:   'int64_t',
    }

# Used when EMITTER_SETTINGS['inline_bitfield'] is set to False.
# t         - Indentation
# fields    - The members of the bitfield
# name      - The name of the bitfield
EXPLICIT_BITFIELD_TEMPLATE = """{t}struct
{t}{{
{fields}
{t}}} {name};"""

ENUM_LITERAL_TEMPLATE = '{t}{name} = {value},'

STRUCT_DEF_CXX = """struct {name}
{{
{members}
}};
"""

STRUCT_DEF_C = """typedef struct
{{
{members}
}} {name};
"""

ENUM_DEF_CXX = """enum class {name}
{{
{members}
}};
"""

EMITTER_SETTINGS = {
    'indentation': '\t',
    'inline_bitfield': False,
    'bitfield_section_type': 'unsigned int',
    'padding_type': 'uint8_t',  # WARNING: Changing this line has unforeseen consequences on generated code!
    'struct_style': STRUCT_DEF_CXX
}